### ISSUE TITLE
create a newLead object on the logic.js file in assets using jqeury to grab the values from your input form

### ISSUE THREAD

**Issue by georgeraymond92** [kayhon/seniorlivingservice#11]

**Comment by georgeraymond92** [comment]
check the public/asssets/js/cats.js file on the cats app for reference

**Comment by georgeraymond92** [comment]
go ahead and work on the ajax post method once you get finish and use console.log to test the newLead object

**Comment by ulyssehakiza** [comment]
seniorlivingservice/public/assets/js/senior.js.
ajax has been created!
